<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findLastTen() :array
    {
        $qb = $this->createQueryBuilder('a')
            ->addOrderBy('a.curentDate', 'DESC');
        $qb->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $userId
     * @return array
     */
    public function findArticleByUser($userId) :array
    {
        $qb = $this->createQueryBuilder('a')
            ->addOrderBy('a.curentDate', 'DESC')
            ->where('a.reporter  = :identifier')
            ->setParameter('identifier', $userId)

        ;
        $qb->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }
}
