<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastTen()
    {
        $qb = $this->createQueryBuilder('a')
            ->addOrderBy('a.curentDate', 'DESC');
        $qb->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }
}
