<?php
/**
 * Created by PhpStorm.
 * User: contact@smaine.me
 * Date: 13/10/2017
 * Time: 19:57
 */

namespace AppBundle\Repository;


/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
}
